services:
  postgres:
    image: ghcr.io/${GITHUB_USER}/nodeauth-postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  backend:
    image: ghcr.io/${GITHUB_USER}/nodeauth-backend:latest
    restart: always
    ports:
      - "6060:6060"
    depends_on:
      - postgres
    environment:
      - SERVER_PORT=6060
      - CLIENT_URL=http://localhost:5173
      - SESSION_SECRET=${SESSION_SECRET}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=postgres
      - DB_NAME=${POSTGRES_DB}

  frontend:
    image: ghcr.io/${GITHUB_USER}/nodeauth-frontend:latest
    restart: always
    ports:
      - "5173:5173"