FROM postgres:latest

COPY ./backend/src/db/migrations/01_initial_schema.sql /docker-entrypoint-initdb.d/

ENV POSTGRES_USER=${POSTGRES_USER}
ENV POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
ENV POSTGRES_DB=${POSTGRES_DB}