services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=dai
      - POSTGRES_PASSWORD=Bubumitho01.
      - POSTGRES_DB=nodelogin
    ports:
      - "5432:5432"
    volumes:
      - ./backend/src/db/migrations/01_initial_schema.sql:/docker-entrypoint-initdb.d/01_initial_schema.sql

  backend:
    build: ./backend
    restart: always
    ports:
      - "6060:6060"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
    environment:
      - SERVER_PORT=6060
      - CLIENT_URL=http://localhost:5173
      - SESSION_SECRET=Daikokatiramrosessionsecret01.
      - DB_USER=dai
      - DB_PASSWORD=Bubumitho01.
      - DB_HOST=postgres
      - DB_NAME=nodelogin

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules