name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push nodeauth-frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./Dockerfile
          push: true
          tags: ghcr.io/bababubudev/nodeauth-frontend:latest

      - name: Build and push nodeauth-backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./Dockerfile
          push: true
          tags: ghcr.io/bababubudev/nodeauth-backend:latest
