name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Fetch code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Build
        uses: docker/setup-buildx-action@v3

      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Metadata action for Frontend
        uses: docker/metadata-action@v5.0.0
        id: frontend-meta
        with:
          images: "${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}"
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=branch

      - name: Build and push Docker Frontend images
        uses: docker/build-push-action@v5.0.0
        with:
          context: ./frontend
          file: ./frontend/DockerFile
          push: true
          tags: ${{ steps.frontend-meta.outputs.tags }}
          labels: ${{ steps.frontend-meta.outputs.labels }}

      - name: Docker Metadata action for Backend
        uses: docker/metadata-action@v5.0.0
        id: backend-meta
        with:
          images: "${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}"
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=branch

      - name: Build and push Docker Backend images
        uses: docker/build-push-action@v5.0.0
        with:
          context: ./backend
          file: ./backend/DockerFile
          push: true
          tags: ${{ steps.backend-meta.outputs.tags }}
          labels: ${{ steps.backend-meta.outputs.labels }}
